apiVersion: v1
kind: Pod
metadata:
  name: kaniko
spec:
  restartPolicy: Never
  containers:
  - name: kaniko
    image: gcr.io/kaniko-project/executor:latest
    # command: [ "/bin/sh", "-c", "--" ] <-- nao funfa com essa img do kaniko
    # args: [ "while true; do sleep 30; done;" ]
    args: ["--context=git://github.com/azattar/k8s_jupyterlab.git",
            "--dockerfile=/Dockerfile",
            #"--destination=k8s_jpytr:beta"] # replace with your dockerhub account
            "--destination=docker.io/azattar/jupyterlab:tagtest"] # replace with your dockerhub account
#    args: ["--dockerfile=/workspace/dockerfile",
#            "--context=dir://workspace",
#            "--destination=<user-name>/<repo>"] # replace with your dockerhub account
    volumeMounts:
      - name: registry-credential
        mountPath: /kaniko/.docker
        readOnly: true
#       - name: dockerfile-storage
#         mountPath: /workspace
  volumes:
    - name: registry-credential
      secret:
        secretName: registry-credential
        items:
          - key: .dockerconfigjson
            path: config.json
  #     - name: dockerfile-storage
  #       persistentVolumeClaim:
  #         claimName: dockerfile-claim
